char *starncat(char *dest, const char *src,int count);
int my_strncmp(const char *cs, const char *ct, int count);
char *skipspaces(const char *str);
char *strims(const char *str);
char *starrchr(const char *s, int c);
char *starnchr(const char *s, int c,int count);
int my_strlen(const char *s);
void  *my_memset(void *s, int c, int count);
char *starchrnul(const char *s, int c);
char *starchr(const char *s, int c);
int starcmp(const char *cs, const char *ct);
char *starcpy(char *dest, const char *src);
int my_strncasecmp(const char *s1, const char *s2, int len);
